name: qfit

channels:
  - conda-forge
  
dependencies:
  - python>=3.9
  - numpy>=1.20,<2
  - scipy
  - cvxpy
  - scip==9.1
  - pandas>=1.2
  - pyparsing>=2.2.0
  - cvxopt
  - tqdm
  - cctbx-base
  - rdkit
  - molmass
